name: Build and Push to DockerHub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to registery
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kasunsjc/flask-python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}